### ISSUE TITLE
[New Resource] - TakeShape Headless GraphQL CMS

### ISSUE THREAD

**Issue by mcat** [brob/butmyclientwants.com#12]
## Title
TakeShape

## Author
TakeShape Inc.

## URL
https://www.takeshape.io/

## Description (just a couple sentences)
TakeShape is a Headless GraphQL CMS and SSG. TakeShape works great with Gatsby. 

## Type (tutorial, tool, article, video)
tool

**Comment by brob** [comment]
Published! Thanks so much for the resource! I see your a co-founder of TakeShape. If you want to pick one of your Tutorials to post here, too, that'd be A-OK by me!

Just post it as another Issue and I'll get it up
