### ISSUE TITLE
How to add a contact form to a static website

### ISSUE THREAD

**Issue by miguejarias** [brob/butmyclientwants.com#22]
## Title

How to add a contact form to a static website

## Author

Silvestar Bistrović

## URL

 https://www.codementor.io/@malimirkeccita/how-to-add-a-contact-form-to-a-static-website-wyl9gsuha

## Description

In this article, you'll learn how to add a contact form with the more advanced form service "Kwes Forms", while also learning about its other unique building features.

## Type

Tutorial

**Comment by brob** [comment]
Added
