### ISSUE TITLE
How to create a multi-step form the easy way

### ISSUE THREAD

**Issue by miguejarias** [brob/butmyclientwants.com#23]
## Title

How to create a multi-step form the easy way

## Author

Silvestar Bistrović

## URL

https://dev.to/starbist/how-to-create-a-multi-step-form-the-easy-way-51cp

## Description

Adding a mult-step form to any site could be daunting. Kwes Forms offers the easiest solution on the web and it works great with static sites.

## Type 

tutorial

**Comment by brob** [comment]
added
