### ISSUE TITLE
Add blog post to user generated content section

### ISSUE THREAD

**Issue by remotesynth** [brob/butmyclientwants.com#25]
## Title
Creating a JAMstack Site with Open Authoring Using Netlify CMS

## Author
Brian Rinaldi

## URL
https://www.stackbit.com/blog/open-authoring-netlifycms/

## Description (just a couple sentences)
How create a community site with the JAMstack that anyone can edit and contribute using NetlifyCMS's open authoring.

## Type (tutorial, tool, article, video)
tutorial

**Comment by brob** [comment]
added
