### ISSUE TITLE
Add Arengu to form services

### ISSUE THREAD

**Issue by jacobovidal** [brob/butmyclientwants.com#34]
## Title

Arengu

## Author

Arengu

## URL

https://www.arengu.com

## Description (just a couple sentences)

Build signup and login forms with Arengu, enable social login, add 2FA or use passwordless flows to authenticate users with your API or identity provider.

## Type (tutorial, tool, article, video)
Tool

**Comment by brob** [comment]
Added via PR #35 

Thanks so much for contributing!
